version: "3.9"

networks:
  currency:
    name: currency
    driver: bridge

services:
  app:
    container_name: currency-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    depends_on:
      - postgres
    networks:
      - currency

  postgres:
    container_name: currency-db
    image: postgres:15
    restart: always
    volumes:
      - ./docker/postgres/data:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - currency

  web:
    container_name: currency-web
    image: nginx:stable-alpine
    restart: always
    ports:
      - "8088:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - currency

  # Database management with pgAdmin
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: currency-pgAdmin
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
  #     - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - postgres
  #   networks:
  #     - currency

  # Database management with Adminer
  adminer:
    container_name: currency-adminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - currency